// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdtwkbjcdmlkztvgoazi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkdHdrYmpjZG1sa3p0dmdvYXppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1NTE0NjgsImV4cCI6MjA3ODEyNzQ2OH0.opayPn_2F97aBr2k14M__EoWM6RNvXIAiopLjBPiJXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});